apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "roxy-wi.migrationName" . }}
  labels:
    {{- include "roxy-wi.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.migrations.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        {{- include "roxy-wi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: OnFailure
      automountServiceAccountToken: false
      serviceAccountName: {{ include "roxy-wi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: {{ include "roxy-wi.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["migrate"]
          env:
            {{- include "roxy-wi.commonEnv" . | nindent 12 }}
          {{- $envFrom := include "roxy-wi.commonEnvFrom" . }}
          {{- if $envFrom }}
          envFrom:
            {{- $envFrom | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            {{- include "roxy-wi.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "roxy-wi.volumes" . | nindent 8 }}
