{{- if or .Values.bootstrapAdminPassword (and .Values.rabbitmq.environmentOverride (not .Values.rabbitmq.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roxy-wi.runtimeSecretName" . }}
  labels:
    {{- include "roxy-wi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.rabbitmq.environmentOverride (not .Values.rabbitmq.existingSecret) }}
  ROXYWI_RABBITMQ_HOST: {{ .Values.rabbitmq.host | quote }}
  ROXYWI_RABBITMQ_PORT: {{ .Values.rabbitmq.port | quote }}
  ROXYWI_RABBITMQ_VHOST: {{ .Values.rabbitmq.vhost | quote }}
  ROXYWI_RABBITMQ_USER: {{ .Values.rabbitmq.username | quote }}
  ROXYWI_RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | quote }}
  {{- end }}
  {{- with .Values.bootstrapAdminPassword }}
  ROXYWI_BOOTSTRAP_ADMIN_PASSWORD: {{ . | quote }}
  {{- end }}
{{- end }}
