{{- if not .Values.existingConfigSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "roxy-wi.configSecretName" . }}
  labels:
    {{- include "roxy-wi.labels" . | nindent 4 }}
type: Opaque
stringData:
  roxy-wi.cfg: |
    {{- include "roxy-wi.config" . | trim | nindent 4 }}
{{- end }}
