---
- name: Create NGINX section
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  roles:
    - role: nginx_section
